### ISSUE TITLE
几个建议

### ISSUE THREAD

**Issue by nobugreporter** [44vogan/Px-Robot#4]
1.希望能加入文字识别
2.希望能增加识别到图片/文字后，鼠标自动移动/单击到对应图片/文字上（作为拾取功能）
3.希望能加入区域图片匹配，我在使用时发现可能匹配特征不够，还是会出现匹配不到的情况，希望能加入区域图片对比来实现
4.希望能加入快速禁用一个模块，写多了之后，想测试其中一部分，比较麻烦。

**Comment by 44vogan** [comment]
- 图案检测依赖不同，会做另外一个软件https://github.com/44vogan/Im-Robot
- 禁用和测试功能会在后面加入，谢谢
